appservice/deploy-to-deployment-slot/pom.xml
appservice/jboss-eap-helloworld/pom.xml
appservice/tomcat-helloworld/pom.xml
pom.xml
spring-cloud/helloworld/pom.xml

This PR fixes #99. `example.postfix` has been moved to the parent `pom.xml`.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
Deploy the `javase-quarkus` application with:
```
mvn azure-webapp:deploy
```

Moving postfix to the parent pom

---

acr/create-acrpull-service-principal/README.md

[this fix](https://github.com/Azure-Samples/java-on-azure-examples/commit/5fa89b1e7ccd56ba97db9487984de878bc129df5) for issue #83 missed part of the update "az ad sp show -> az ad sp list".

fixed mismatch in workflow.skip vs. workflow.run

---

CONTRIBUTING.md

* Adding the title of the project
* Fixing the master branch name to main
* One line per sentence
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Fixing by adding a title and changing the branch name to main

---

compute/appservice/tomcat-helloworld/README.md

* Fixes #151
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Improves readme of tomcat hello

---

.editorconfig
compute/appservice/create-deployment-slot/README.md
compute/appservice/tomcat-helloworld/README.md

* Fixes #153
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Improves readme of create deployment slot

---

compute/appservice/deploy-to-deployment-slot/README.md

* Fixes #155
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Improves readme deploy to deploylement slot

---

compute/appservice/docker-glassfish/README.md
compute/appservice/docker-graalvm/README.md
compute/appservice/docker-tomcat/README.md
compute/appservice/docker-wildfly/README.md

* Fixes #163
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

Fix wrong paths on includes

---

compute/appservice/delete-webapp/README.md

* Fixes #165
```
[ ] Yes
[x] No
```
*  Workflow should pass

Fix workflow due to wrong shell

---

storage/storage/enable-static-website/README.md

* Fixes #167
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
mvn clean install
```
* Test the code
```
```
Verify that the following are valid
* ...

Add resource group to the readme

---

analytics/eventhubs/receive-event/pom.xml
analytics/eventhubs/receive-event/src/main/java/examples/azure/eventhubs/receiveevent/ReceiveEvent.java
analytics/eventhubs/send-event/pom.xml
analytics/eventhubs/send-event/src/main/java/examples/azure/eventhubs/sendevent/SendEvent.java

* Fixes #169
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
mvn clean install
```
* Test the code
```
```
Verify that the following are valid
* ...

Check that the environment variables are set

---

compute/appservice/create-deployment-slot/README.md
compute/appservice/delete-webapp/README.md
compute/appservice/deploy-to-deployment-slot/README.md
compute/appservice/tomcat-helloworld/README.md
containers/acr/graalvm/README.md

* Fixes #174
```
[ ] Yes
[x] No
```

Fix READMEs after refactoring

---

.github/workflows/_cleanup.yml
.github/workflows/_generate_workflows.yml
.github/workflows/_stale.yml

* Fixes 176
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
mvn clean install
```
* Test the code
```
```
Verify that the following are valid
* ...

Renaming the name of the workflow

---

compute/appservice/docker-glassfish/README.md
compute/appservice/docker-graalvm/README.md
compute/appservice/docker-jetty/README.md
compute/appservice/docker-payara/README.md
compute/appservice/docker-tomcat/README.md
compute/appservice/docker-wildfly/README.md
compute/appservice/javase-quarkus/README.md
compute/appservice/javase-springboot/README.md
compute/appservice/jboss-eap-helloworld/README.md
containers/acr/jetty/README.md

* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Adding resource group to the cli

---

compute/appservice/deploy-to-deployment-slot/README.md

* Fixes #180
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

Fixing deploy-to-deployment-slot workflow

---

compute/appservice/docker-glassfish/README.md
compute/appservice/docker-graalvm/README.md
compute/appservice/docker-jetty/README.md
compute/appservice/docker-payara/README.md
compute/appservice/docker-tomcat/README.md
compute/appservice/docker-wildfly/README.md

* Fixes #183
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```

Using the image variable

---

containers/acr/graalvm/README.md

* Fixes #185
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

Fix directory path

---

.github/workflows/analytics_adx_ingest-client_README_md.yml
.github/workflows/monitor_log-analytics_create-workspace_README_md.yml
.script/analytics_adx_ingest-client.sh
.script/monitor_log-analytics_create-workspace.sh
README.md
analytics/adx/ingest-client/README.md
monitor/log-analytics/create-workspace/README.md
monitor/log-analytics/create-workspace/pom.xml
monitor/log-analytics/pom.xml
monitor/pom.xml
pom.xml

New Log Analytics sample
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```

Log nalaytics

---

appconfig/README.md
appconfig/add-key-value/README.md
appconfig/add-key-value/pom.xml
appconfig/create/README.md
appconfig/create/pom.xml
appconfig/pom.xml

Add App Configuration examples
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
mvn clean install
```
* Test the code
```
```
Verify that the following are valid
* Create a resource group
* Create an App configuration
* Add a key/value
* Check the value is there

Crate app config and add key value

---

container/wildfly/README.md
container/wildfly/pom.xml

Acknowledging issue and disabling workflow until we can address it

In progress #358 - Fix WildFly example

---

pom.xml

Fix: https://github.com/Azure-Samples/java-on-azure-examples/issues/502

Bump Azure SDK
